import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import {AppProvider} from "@/contexts/appContext";
import 'animate.css';
import {cardsInfo} from "@/data/cards";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Memory Game',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {

    return (
        <html lang="en">
        <body className={inter.className}>
        <AppProvider cardsInfo={cardsInfo}>
            <main className="h-screen">
                {children}
            </main>
        </AppProvider>
        </body>
        </html>
    )
}
